spring:
  application:
    name: xbird-cloud-netflix-eureka-client
server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
    metadataMap:
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/