spring:
  application:
    name: xbird-cloud-netflix-turbine
server:
  port: 8030
eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api/eureka/**
      serviceId: xbird-cloud-netflix-eureka-client
    api-b:
      path: /api/feign/**
      serviceId: xbird-cloud-openfeign