spring:
  application:
    name: xbird-cloud-netflix-zuul
server:
  port: 8085
eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api/eureka/**
      serviceId: xbird-cloud-netflix-eureka-client
    api-b:
      path: /api/feign/**
      serviceId: xbird-cloud-openfeign