spring:
  application:
    name: xbird-cloud-netflix-ribbon
server:
  port: 8010
eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/