spring:
  application:
    name: xbird-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          searchPaths: respo
      label: master
server:
  port: 8888
eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/