spring:
  application:
    name: xbird-cloud-config-client
  cloud:
    config:
      name: config-client
      label: master
      profile: dev
      discovery:
        serviceId: xbird-cloud-config-server
server:
  port: 8889
eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/