spring:
  application:
    name: xbird-cloud-consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
server:
  port: 8501