spring:
  application:
    name: xbird-cloud-openfeign
server:
  port: 8086
eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true